/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private int IdUser;
    private boolean IsLogged;
    
    public Main() {
        initComponents();
        btEditeaza.setEnabled(false);
        btSterge.setEnabled(false);
        logOut.setEnabled(false);
        
        IsLogged = false;
        SetInterface(IsLogged);
        
        IdUser = 0;
    }
    
    private void SetInterface(boolean value){
        tFieldCauta.setEnabled(value);
        btCauta.setEnabled(value);
        
        btAdauga.setEnabled(value);
        btEditeaza.setEnabled(value);
        btSterge.setEnabled(value);
        btStergeCampuri.setEnabled(value);
        
        tFieldNume.setEnabled(value);
        tFieldPrenume.setEnabled(value);
        tFieldEmail.setEnabled(value);
        tFieldTelefon.setEnabled(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDialog = new javax.swing.JDialog();
        labelUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        labelParola = new javax.swing.JLabel();
        tfParola = new javax.swing.JPasswordField();
        bLogIn = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        formular = new javax.swing.JPanel();
        labelNume = new javax.swing.JLabel();
        labelPrenume = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelTelefon = new javax.swing.JLabel();
        tFieldNume = new javax.swing.JTextField();
        tFieldPrenume = new javax.swing.JTextField();
        tFieldEmail = new javax.swing.JTextField();
        tFieldTelefon = new javax.swing.JTextField();
        cautare = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tFieldCauta = new javax.swing.JTextField();
        btCauta = new javax.swing.JButton();
        butoane = new javax.swing.JPanel();
        btAdauga = new javax.swing.JButton();
        btEditeaza = new javax.swing.JButton();
        btSterge = new javax.swing.JButton();
        btStergeCampuri = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        Cont = new javax.swing.JMenu();
        logIn = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        logOut = new javax.swing.JMenuItem();

        loginDialog.setTitle("Log In");
        loginDialog.setLocationByPlatform(true);
        loginDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUsername.setText("Username");

        labelParola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelParola.setText("Parola");

        bLogIn.setText("Log In");
        bLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogInActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsername)
                            .addComponent(labelParola))
                        .addGap(43, 43, 43)
                        .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUsername)
                            .addComponent(tfParola, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(loginDialogLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParola)
                    .addComponent(tfParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLogIn)
                    .addComponent(bExit))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("");
        setLocationByPlatform(true);
        setResizable(false);

        labelNume.setText("Nume");

        labelPrenume.setText("Prenume");

        labelEmail.setText("Email");

        labelTelefon.setText("Telefon");

        javax.swing.GroupLayout formularLayout = new javax.swing.GroupLayout(formular);
        formular.setLayout(formularLayout);
        formularLayout.setHorizontalGroup(
            formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularLayout.createSequentialGroup()
                        .addComponent(labelNume)
                        .addGap(26, 26, 26)
                        .addComponent(tFieldNume, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addGroup(formularLayout.createSequentialGroup()
                        .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrenume)
                            .addComponent(labelEmail)
                            .addComponent(labelTelefon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFieldPrenume)
                            .addComponent(tFieldEmail)
                            .addComponent(tFieldTelefon))))
                .addContainerGap())
        );
        formularLayout.setVerticalGroup(
            formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNume)
                    .addComponent(tFieldNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenume)
                    .addComponent(tFieldPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(tFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefon)
                    .addComponent(tFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Cauta utilizator");

        btCauta.setText("Cauta");
        btCauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCautaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cautareLayout = new javax.swing.GroupLayout(cautare);
        cautare.setLayout(cautareLayout);
        cautareLayout.setHorizontalGroup(
            cautareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(cautareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFieldCauta, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautareLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCauta)
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        cautareLayout.setVerticalGroup(
            cautareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cautareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFieldCauta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCauta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAdauga.setText("Adauga");
        btAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdaugaActionPerformed(evt);
            }
        });

        btEditeaza.setText("Editeaza");
        btEditeaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditeazaActionPerformed(evt);
            }
        });

        btSterge.setText("Sterge utilizator");
        btSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStergeActionPerformed(evt);
            }
        });

        btStergeCampuri.setText("Sterge campuri");
        btStergeCampuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStergeCampuriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout butoaneLayout = new javax.swing.GroupLayout(butoane);
        butoane.setLayout(butoaneLayout);
        butoaneLayout.setHorizontalGroup(
            butoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butoaneLayout.createSequentialGroup()
                .addComponent(btAdauga, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEditeaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSterge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btStergeCampuri))
        );
        butoaneLayout.setVerticalGroup(
            butoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btAdauga)
                .addComponent(btEditeaza)
                .addComponent(btSterge)
                .addComponent(btStergeCampuri))
        );

        Cont.setText("Cont");

        logIn.setText("Log In");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        Cont.add(logIn);
        Cont.add(separator);

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        Cont.add(logOut);

        menu.add(Cont);

        setJMenuBar(menu);
        
        labelConnectedUsers = new JLabel("Utilizatori inregistrati:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(4)
        							.addComponent(cautare, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(labelConnectedUsers)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(formular, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(73)
        					.addComponent(butoane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(48)
        					.addComponent(formular, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(88)
        					.addComponent(labelConnectedUsers)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(cautare, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addComponent(butoane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(27, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdaugaActionPerformed

        if(btAdauga.getText() == "Adauga"){
            if(tFieldNume.getText().isEmpty() || tFieldPrenume.getText().isEmpty() || tFieldEmail.getText().isEmpty() || tFieldTelefon.getText().isEmpty()){
                     JOptionPane.showMessageDialog(
                        this,
                        "Toate campurile sunt obligatorii. ",
                        "Atentie",
                        JOptionPane.WARNING_MESSAGE
                 );
            }
            else{
            	UserService.addUser(new User(tFieldNume.getText(),tFieldPrenume.getText(),tFieldEmail.getText(),tFieldTelefon.getText()));
        
                JOptionPane.showMessageDialog(
                        this,
                        "Utilizatorul " + tFieldNume.getText() + " " + tFieldPrenume.getText() + " a fost adaugat.",
                        "Adaugat",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                ResourceSingleton resource = ResourceSingleton.getInstance();
                
                labelConnectedUsers.setText("Utilizatori inregistrati: " + resource.getNrUsers());
            }
        }
        else if(btAdauga.getText() == "Update"){
            User user = new User(tFieldNume.getText(),tFieldPrenume.getText(),tFieldEmail.getText(),tFieldTelefon.getText());
            user.setId(IdUser);
            
            UserService.updateUser(user);
            
            JOptionPane.showMessageDialog(
                    this,
                    "Utilizatorul " + tFieldNume.getText() + " " + tFieldPrenume.getText() + " a fost modificat.",
                    "Modificat",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            btAdauga.setText("Adauga");
            btAdauga.setEnabled(false);
            
            btEditeaza.setText("Editeaza");
            
            tFieldNume.setEditable(false);
            tFieldPrenume.setEditable(false);
            tFieldEmail.setEditable(false);
            tFieldTelefon.setEditable(false);
            
        }

    }//GEN-LAST:event_btAdaugaActionPerformed

    private void btCautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCautaActionPerformed
        if(tFieldCauta.getText() != null && !tFieldCauta.getText().isEmpty()){
           
            User user = UserService.getUser(tFieldCauta.getText());
            
            if(user == null){
                JOptionPane.showMessageDialog(
                    this,
                    "Utilizatorul " + tFieldCauta.getText() + " nu a fost gasit.",
                    "Eroare",
                    JOptionPane.ERROR_MESSAGE
                );
        
            }
            else{
                                
            IdUser = user.getId();
            
            tFieldNume.setText(user.getLastname());
            tFieldPrenume.setText(user.getFirstname());
            tFieldEmail.setText(user.getEmail());
            tFieldTelefon.setText(user.getPhone());
            tFieldCauta.setText("");
            
            tFieldNume.setEditable(false);
            tFieldPrenume.setEditable(false);
            tFieldEmail.setEditable(false);
            tFieldTelefon.setEditable(false);
            
            btAdauga.setEnabled(false);
            btEditeaza.setEnabled(true);
            btSterge.setEnabled(true);
            }
       
        }
    }//GEN-LAST:event_btCautaActionPerformed

    private void btEditeazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditeazaActionPerformed
        if(btEditeaza.getText() == "Editeaza"){
            tFieldNume.setEditable(true);
            tFieldPrenume.setEditable(true);
            tFieldEmail.setEditable(true);
            tFieldTelefon.setEditable(true);

            btEditeaza.setText("Anuleaza");

            btAdauga.setEnabled(true);
            btAdauga.setText("Update");
            
            btStergeCampuri.setEnabled(false);
        }
        else if(btEditeaza.getText() == "Anuleaza"){
            tFieldNume.setEditable(false);
            tFieldPrenume.setEditable(false);
            tFieldEmail.setEditable(false);
            tFieldTelefon.setEditable(false);

            btEditeaza.setText("Editeaza");
            
            btStergeCampuri.setEnabled(true);

            btAdauga.setEnabled(false);
            btAdauga.setText("Adauga");
        }

    }//GEN-LAST:event_btEditeazaActionPerformed

    private void btStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStergeActionPerformed
        if(IdUser != 0){
        	UserService.deleteUser(IdUser);
            
            JOptionPane.showMessageDialog(
                this,
                "Utilizatorul " + tFieldNume.getText() + " " + tFieldPrenume.getText() + " a fost sters.",
                "Sters",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            ResourceSingleton resource = ResourceSingleton.getInstance();
            
            labelConnectedUsers.setText("Utilizatori inregistrati: " + resource.getNrUsers());
            
            IdUser = 0;
            
            tFieldNume.setText("");
            tFieldPrenume.setText("");
            tFieldEmail.setText("");
            tFieldTelefon.setText("");
            
            tFieldNume.setEditable(true);
            tFieldPrenume.setEditable(true);
            tFieldEmail.setEditable(true);
            tFieldTelefon.setEditable(true);
            
            btAdauga.setEnabled(true);
            btEditeaza.setEnabled(false);
            btSterge.setEnabled(false);
        }
    }//GEN-LAST:event_btStergeActionPerformed

    private void btStergeCampuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStergeCampuriActionPerformed
            tFieldNume.setText("");
            tFieldPrenume.setText("");
            tFieldEmail.setText("");
            tFieldTelefon.setText("");
            
            tFieldNume.setEditable(true);
            tFieldPrenume.setEditable(true);
            tFieldEmail.setEditable(true);
            tFieldTelefon.setEditable(true);
            
            btEditeaza.setEnabled(false);
            btSterge.setEnabled(false);
            
            btAdauga.setEnabled(true);
            
            IdUser = 0;
    }//GEN-LAST:event_btStergeCampuriActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        SetInterface(false);
        
        logIn.setEnabled(true);
        logOut.setEnabled(false);
        
        tFieldNume.setText("");
        tFieldPrenume.setText("");
        tFieldEmail.setText("");
        tFieldTelefon.setText("");
    }//GEN-LAST:event_logOutActionPerformed

    private void bLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogInActionPerformed     
        if(!UserService.login(tfUsername.getText(), tfParola.getPassword())){
                JOptionPane.showMessageDialog(
                this,
                "Username-ul sau parola nu este corect.",
                "Atentie",
                JOptionPane.WARNING_MESSAGE
            );
        }
        else{
            loginDialog.setVisible(false);
            
              JOptionPane.showMessageDialog(
                this,
                "Autentificarea a fost realizata cu succes.",
                "Succes",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            SetInterface(true);
            btEditeaza.setEnabled(false);
            btSterge.setEnabled(false);
            logIn.setEnabled(false);
            logOut.setEnabled(true);
            
            tfUsername.setText("");
            tfParola.setText("");
            
            ResourceSingleton resource = ResourceSingleton.getInstance();
            
            
            labelConnectedUsers.setText("Utilizatori inregistrati: " + resource.getNrUsers());

        }
    }//GEN-LAST:event_bLogInActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        loginDialog.setVisible(true);
    }//GEN-LAST:event_logInActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        loginDialog.setVisible(false);
        tfUsername.setText("");
        tfParola.setText("");
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cont;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bLogIn;
    private javax.swing.JButton btAdauga;
    private javax.swing.JButton btCauta;
    private javax.swing.JButton btEditeaza;
    private javax.swing.JButton btSterge;
    private javax.swing.JButton btStergeCampuri;
    private javax.swing.JPanel butoane;
    private javax.swing.JPanel cautare;
    private javax.swing.JPanel formular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNume;
    private javax.swing.JLabel labelParola;
    private javax.swing.JLabel labelPrenume;
    private javax.swing.JLabel labelTelefon;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelConnectedUsers;
    private javax.swing.JMenuItem logIn;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JTextField tFieldCauta;
    private javax.swing.JTextField tFieldEmail;
    private javax.swing.JTextField tFieldNume;
    private javax.swing.JTextField tFieldPrenume;
    private javax.swing.JTextField tFieldTelefon;
    private javax.swing.JPasswordField tfParola;
    private javax.swing.JTextField tfUsername;
}
